@client_secret = ...
@client_id = ...
@pd_project_id = proj_zNsg4Me

# @base_url = https://api.pipedream.com
@base_url = http://localhost:3000
@external_user_id = user_123

### Get OAuth token
# @name getToken
POST {{base_url}}/v1/oauth/token
Content-Type: application/json

{
  "grant_type": "client_credentials",
  "client_id": "{{client_id}}",
  "client_secret": "{{client_secret}}"
}

### Store the token from previous response
@auth_token = {{getToken.response.body.access_token}}

### Use the token to get app info
GET {{base_url}}/v1/apps
Authorization: Bearer {{auth_token}}


# @app_slug = serpapi
# @app_slug = test_hello
# @app_slug = serpdog
@app_slug = slack

### List apps with search query
GET {{base_url}}/v1/apps?q={{app_slug}}&limit=10
Authorization: Bearer {{auth_token}}

###

### Get specific app
GET {{base_url}}/v1/apps/{{app_slug}}
Authorization: Bearer {{auth_token}}

###

### List actions for SerpAPI (Pipedream v1 API)
GET {{base_url}}/v1/connect/{{pd_project_id}}/actions?app={{app_slug}}&limit=100
Authorization: Bearer {{auth_token}}
X-PD-Environment: development

###

### List triggers for SerpAPI (Pipedream v1 API)
GET {{base_url}}/v1/connect/{{pd_project_id}}/triggers?app={{app_slug}}&limit=100
Authorization: Bearer {{auth_token}}
X-PD-Environment: development

@component_slug = slack-send-message
# @component_slug = serpapi_custom-search
# @component_slug = d_L7svdRd4
### Get - App Triggers - Tested
GET {{base_url}}/v1/connect/{{pd_project_id}}/components/{{component_slug}}
Content-Type: application/json
Authorization: Bearer {{auth_token}}
X-PD-Environment: development

### Run SerpAPI search action (Pipedream v1 API)
POST {{base_url}}/v1/connect/{{pd_project_id}}/actions/run
Content-Type: application/json
Authorization: Bearer {{auth_token}}
X-PD-Environment: development

{
  "external_user_id": "{{external_user_id}}",
  "id": "hello_world",
  "configured_props": {
    "serpapi": {
      "authProvisionId": "auth_123"
    },
    "q": "coffee shops near me",
    "engine": "google",
    "name": "google",
    "location": "Austin, Texas"
  }
}

#### Run SerpDog search action (Pipedream v1 API)

POST {{base_url}}/v1/connect/{{pd_project_id}}/actions/run
Content-Type: application/json
Authorization: Bearer {{auth_token}}
X-PD-Environment: development

{
  "external_user_id": "{{external_user_id}}",
  "id": "serpapi-scrape-search",
  "configured_props": {
    "serpapi": {
      "authProvisionId": "apn_key_123"
    },
    "q": "coffee shops near me",
    "engine": "google",
    "name": "google",
    "location": "Austin, Texas"
  }
}

### Generate Token with link to connect with app - Tested
# @name connectionToken
POST {{base_url}}/v1/connect/{{pd_project_id}}/tokens
Content-Type: application/json
Authorization: Bearer {{auth_token}}
X-PD-Environment: development

{
  "external_user_id": "{{external_user_id}}"
}
### Store the token from previous response
@connection_token = {{connectionToken.response.body.token}}

###
GET {{base_url}}/v1/connect/{{pd_project_id}}/auth/oauth/slack/start?connect_token={{connection_token}}
Content-Type: application/json
Authorization: Bearer {{auth_token}}
X-PD-Environment: development

### 
@state=your_state_here
@code=your_slack_code_here
GET {{base_url}}/v1/connect/{{pd_project_id}}/auth/oauth/slack/callback?code=254223766679.9386751552129.07508bcfd2ac416a8d2ac2c628ce7d25906ece4ec4fe192cd36eb0c25b3b2884&state=user_123_1755594037994_0g2ube
Content-Type: application/json
Authorization: Bearer {{auth_token}}
X-PD-Environment: development
{

}

### for "keys" type auth creation
POST {{base_url}}/v1/connect/accounts
Content-Type: application/json
Authorization: Bearer {{auth_token}}
X-PD-Environment: development

{
  "app_slug": "serpapi",
  "cfmap_json": "{\"api_key\": \"your_api_key_here\"}",
  "connect_token": "{{connection_token}}"
}
### 

GET {{base_url}}/v1/connect/{{pd_project_id}}/accounts?app={{app_slug}}&external_user_id={{external_user_id}}&include_credentials=true
Content-Type: application/json
Authorization: Bearer {{auth_token}}
X-PD-Environment: development

{
  
}



### data: [{id: apn_..., name: .. ,updated_at: , created_at: .. ,healthy: true, external_id: .. , app: ..}] , page_info: []
@apn_key = apn_b3975a8bc44e4b4e

### Get App Connected Accounts with sepcific app account or all by remove last ID from URL - Tested
GET {{base_url}}/v1/connect/{{pd_project_id}}/accounts/{{apn_key}}
Content-Type: application/json
Authorization: Bearer {{auth_token}}
X-PD-Environment: development

{
  "external_user_id": "{{external_user_id}}",
  "app": "slack"
}
####
  # "include_credentials": true

GET {{base_url}}/v1/connect/{{pd_project_id}}/accounts?app={{app_slug}}&external_user_id={{external_user_id}}
// is required params??

### Delete the App Account - Tested
DELETE {{base_url}}/v1/connect/{{pd_project_id}}/accounts/{{apn_key}}
Content-Type: application/json
Authorization: Bearer {{auth_token}}
X-PD-Environment: development

### EXTRA


### View recent runs
GET {{base_url}}/admin_logs/runs


### Test with invalid endpoint (should return 404)
GET {{base_url}}/invalid/endpoint

